---

- hosts: all
  become: true
  tasks:

  - name: install apache2 & php Support package
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php }}"  
      state: latest
      update_cache: yes
