---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (centOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOs"

  - name: install updates (centOS)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks: 

  - name: install apache2 & php Support package
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php }}"  
      state: latest

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    package:
      name: "{{ mariadb_package }}"
      state: latest

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
